name: Build Linux program

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install 32bit stuff
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib
    - name: build
      run: gcc -m32 main.c -o piEncrypt
    - name: test executuable
      run: ./piEncrypt 48 5348 946824 PartialHamlet.txt H4M13T.txt -k
    - name: test executuable 2
      run: ./piEncrypt 8379 946824 164302 Random64.txt 54ND0M64.txt -k
    - name: build decrypt
      run: gcc -m32 Decrypt/main.c -o piDecrypt
    - name: test decrypt
      run: ./piDecrypt 48 5348 946824 H4M13T.txt decryptedHamlet.txt -k
    - name: check decrypt
      run: diff -u PartialHamlet.txt decryptedHamlet.txt
    - uses: actions/upload-artifact@v4
      with:
          name: piEncrypt
          path: piEncrypt
    - uses: actions/upload-artifact@v4
      with:
          name: encryptedHamlet
          path: H4M13T.txt
    - uses: actions/upload-artifact@v4
      with:
          name: Encrypted64
          path: 54ND0M64.txt
