name: Build Unix program

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install 32bit stuff
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib
    - name: build
      run: gcc -m32 main.c -o piEncrypt
    - name: test executuable
      run: ./piEncrypt
    - uses: actions/upload-artifact@v4
      with:
          name: piEncrypt
          path: piEncrypt
